LOCAL_PATH := $(my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := SimpleGallery
LOCAL_SRC_FILES := SimpleGallery.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_CERTIFICATE := platform
LOCAL_PRIVILEGED_MODULE := true
LOCAL_PRODUCT_MODULE := true
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT_APPS)

include $(BUILD_PREBUILT)
